# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: anomia
email: lagrimaescrita@gmail.com
description: > I'm a newbie livecoder from Madrid # this means to ignore newlines until "baseurl:"

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
#url: "http://username.github.io"
#baseurl: ""

# If you are building a GitHub project page then use these settings:
url: "https://rubentr.github.io/anomia" 
#"https://rubentr.github.io/intonarumori/" 
#the base hostname "http://username.github.io/projectname"
baseurl: "/anomia/" 
#/intonarumori/ #the subpath of your site, "/projectname"

twitter_username: rubentobalina
github_username: rubentr
website: chuletitaspinguino.wordpress.com
Soundcloud_userID: user-516707540
#Youtube_username: lagrimaescrita

# Important settings
# assets:
# sources:
#   - assets/fonts
#   - assets/img
#   - assets/stylesheets

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
#    - soundcloud_sound

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
