# Welcome to Jekyll!

# Site settings
title: anomia, codificada
sitename: anomia
email: lagrimaescrita@gmail.com
description: >

# the subpath of your site, e.g. /blog
baseurl: "" 
# the base hostname & protocol for your site
url: "http://rubentr.github.io" 

# Missing timezone in metadata date can lead to wrong date in url
timezone: Europe/Madrid 
